apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bsa-pro
  template:
    metadata:
      labels:
        app: bsa-pro
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.1
          ports:
            - containerPort: 80