apiVersion: v1
kind: Namespace
metadata:
  name: bsa-pro
  labels:
    name: bsa-pro
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    namespace: bsa-pro
spec:
  containers:
    - name: nginx
      image: nginx:1.17.0
      ports:
        - containerPort: 80