apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: backend
  template:
    metadata:
      labels:
        k8s-app: backend
    spec:
      containers:
      - name: k8s-app-backend
        image: lenchv/k8s-app-backend:0.0.1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-app-backend
spec:
  selector:
    k8s-app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
