apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsa-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
        containers:
        - name: simpleapp
          image: dgkanatsios/simpleapp
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bsa-app
  labels:
    app: test
spec:
  selector:
    app: test
  ports:
  - protocol: TCP
    port: 9876
    targetPort: 8080